import { launch } from 'puppeteer-core';
const browser = await launch({ executablePath: '/usr/bin/google-chrome-stable', headless: 'new', args: ['--no-sandbox','--disable-gpu','--window-size=1300,900'] });
const page = await browser.newPage();
await page.setViewport({ width: 1300, height: 900 });
const logs=[];
page.on('console', m=>{ if(m.text().includes('[DBG]')) logs.push(m.text()); });
await page.goto('http://localhost:5173/library-demo.html', { waitUntil: 'networkidle0' });
await page.evaluate(() => { window.confirm = () => true; });
await new Promise(r => setTimeout(r, 2500));
await page.evaluate(() => [...document.querySelectorAll('.score-card:not(.new-card)')][0]?.click());
await new Promise(r => setTimeout(r, 1500));
const cur = () => page.evaluate(() => document.querySelectorAll('.ms-blk:not(.ms-leave)').length);
while (await cur() > 1) { await page.evaluate(() => { const b=[...document.querySelectorAll('.ms-blk')].pop(); b.dispatchEvent(new MouseEvent('mouseenter',{bubbles:true})); b.querySelector('.ms-del')?.click(); }); await new Promise(r=>setTimeout(r,70)); }
while (await cur() < 8) { await page.evaluate(() => document.querySelector('.ms-add')?.click()); await new Promise(r=>setTimeout(r,50)); }
await new Promise(r=>setTimeout(r,400));
await page.evaluate(() => window.__ms.setSelection(2, 2));
await new Promise(r => setTimeout(r, 600));
const gripR = await page.$('.ms-grip-r');
const gBox = await gripR.boundingBox();
const t6 = await page.evaluate(() => { const b=document.querySelector('.ms-blk[data-idx="6"]'); const r=b.getBoundingClientRect(); return {x:r.left+r.width/2,y:r.top+r.height/2}; });
await page.mouse.move(gBox.x+gBox.width/2, gBox.y+gBox.height/2);
await page.mouse.down();
await page.mouse.move(t6.x, gBox.y+gBox.height/2);
await new Promise(r=>setTimeout(r,200));
const before = await page.evaluate(() => document.querySelector('.ms-sel').style.transition);
await page.mouse.up();
await new Promise(r=>setTimeout(r,500));
const after = await page.evaluate(() => document.querySelector('.ms-sel').style.transition);
console.log('拖拽前 sel.trans='+before, '抬手后 sel.trans='+after);
console.log('DBG日志:', logs.join(' | ') || '无');
await browser.close();
